/**
 * MIPROv2 — Multi-prompt Instruction PRoposal Optimizer v2.
 *
 * Promoted from `examples/MIPROv2/` to a first-class optimizer. Three stages,
 * mirroring DSPy's MIPROv2:
 *   1. propose `numCandidateInstructions` candidate instruction strings
 *      (via the configured LM when available, plus a deterministic template set
 *      and the program's own prompt as fallbacks);
 *   2. bootstrap few-shot demos by running the program over the trainset and
 *      keeping the ones that score ≥ `minDemoScore`, plus labeled demos;
 *   3. search over (instruction × demo-subset) combinations for `numTrials`,
 *      scoring each candidate on a minibatch of the trainset with the metric,
 *      and return the best `OptimizedModule`.
 *
 * Random search over the (small) grid is the pragmatic equivalent of DSPy's
 * `auto='light'`; a Bayesian surrogate can be layered on later.
 */
import * as fs from 'fs';
import * as path from 'path';
import { Module } from '../core/module';
import { Pipeline } from '../core/pipeline';
import { Signature } from '../core/signature';
import { Optimizer, OptimizerConfig, TrainingExample, MetricFunction } from './base';
import { getLM } from '../index';
import { AgentDBClient } from '../memory/agentdb/client';
import { CompilationTracer } from '../observability/tracer';

/**
 * Resolve and validate a file path used for saving/loading optimizer state.
 * Prevents path traversal by rejecting paths that contain null bytes and
 * normalising any ".." components.
 */
function safeResolvePath(userPath: string): string {
  if (userPath.includes('\0')) {
    throw new Error('Invalid path: null bytes are not permitted');
  }
  return path.resolve(userPath);
}

export interface MIPROv2Config extends OptimizerConfig {
  /** How many candidate instructions to consider (default 5). */
  numCandidateInstructions?: number;
  /** How many (instruction × demo-subset) combinations to evaluate (default 10). */
  numTrials?: number;
  /** Max labeled demos pulled straight from the trainset (default 4). */
  maxLabeledDemos?: number;
  /** Max bootstrapped demos generated by running the program (default 4). */
  maxBootstrappedDemos?: number;
  /** Minimum metric score for a bootstrapped demo to be kept (default 0.5). */
  minDemoScore?: number;
  /** Trainset minibatch size for scoring each candidate (default: all eval examples). */
  minibatchSize?: number;
  /** Deterministic RNG seed for the random search (default 42). */
  seed?: number;
  /**
   * Experience replay: an AgentDB client to persist each compile's best
   * (instruction, score) for a task fingerprint and recall it on later compiles
   * — so the search warm-starts from instructions that worked before, across
   * runs. (`agentdb.LearningSystem`-backed RL bandit over instruction choices is
   * a deeper variant tracked on #8.)
   */
  replayStore?: AgentDBClient;
  /** How many prior best-instructions to recall and prepend to the search (default 3). */
  replayTopK?: number;
  /** Observability: trace this compile's trials (causal chain, AgentDB persistence, optional MLflow). */
  tracer?: CompilationTracer;
}

/** A module whose prompt = instruction + few-shot demos + the input, calling the global LM. */
export class OptimizedModule<TInput extends Record<string, any>, TOutput extends Record<string, any>> extends Module<TInput, TOutput> {
  public readonly instruction: string;
  public readonly demos: TrainingExample<TInput, TOutput>[];

  constructor(name: string, signature: Signature, instruction: string, demos: TrainingExample<TInput, TOutput>[]) {
    super({
      name,
      signature,
      strategy: 'Predict',
      promptTemplate: (input: TInput) => OptimizedModule.buildPrompt(instruction, demos, input),
    });
    this.instruction = instruction;
    this.demos = demos;
  }

  static buildPrompt(instruction: string, demos: Array<{ input: any; output?: any }>, input: any): string {
    const demoText = demos
      .filter((d) => d.output !== undefined)
      .map((d) => `Input: ${JSON.stringify(d.input)}\nOutput: ${JSON.stringify(d.output)}`)
      .join('\n\n');
    const parts = [instruction.trim()];
    if (demoText) parts.push(`Examples:\n${demoText}`);
    parts.push(`Now respond in JSON for:\nInput: ${JSON.stringify(input)}\n\nResponse:`);
    return parts.join('\n\n');
  }

  async run(input: TInput): Promise<TOutput> {
    this.validateInput(input);
    const lm = getLM();
    const response = await lm.generate(this.promptTemplate(input));
    let output: TOutput;
    try {
      output = JSON.parse(response) as TOutput;
    } catch {
      if (this.signature.outputs.length === 1 && this.signature.outputs[0].type === 'string') {
        output = { [this.signature.outputs[0].name]: response } as TOutput;
      } else {
        throw new Error('Failed to parse LM response');
      }
    }
    this.validateOutput(output);
    return output;
  }
}

const DEFAULT_TEMPLATES = [
  'Answer the question carefully and accurately.',
  'Think step by step, then give a concise, correct answer.',
  'Be precise. Use only the information provided. Answer in JSON.',
  'Reason about the input, then output the best answer.',
  'You are an expert. Provide a high-quality, well-structured answer.',
];

/** Tiny deterministic PRNG (mulberry32). */
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface MIPROv2Result {
  instruction: string;
  demos: TrainingExample[];
  score: number;
  trials: Array<{ instruction: string; numDemos: number; score: number }>;
  /** True if the search was seeded with instructions recalled from a replay store. */
  warmStarted: boolean;
  /** How many prior best-instructions were recalled and prepended to the search. */
  recalledInstructions: number;
}

export class MIPROv2<TInput extends Record<string, any>, TOutput extends Record<string, any>> extends Optimizer<TInput, TOutput> {
  protected config: Required<Omit<MIPROv2Config, 'minibatchSize' | 'replayStore' | 'tracer'>> & {
    minibatchSize?: number;
    replayStore?: AgentDBClient;
    tracer?: CompilationTracer;
  };
  private optimizedProgram: OptimizedModule<TInput, TOutput> | null = null;
  private lastResult: MIPROv2Result | null = null;

  constructor(metric: MetricFunction<TInput, TOutput>, config: MIPROv2Config = {}) {
    super(metric, config);
    this.config = {
      maxIterations: 10,
      numThreads: 1,
      debug: false,
      numCandidateInstructions: 5,
      numTrials: 10,
      maxLabeledDemos: 4,
      maxBootstrappedDemos: 4,
      minDemoScore: 0.5,
      seed: 42,
      replayTopK: 3,
      ...config,
    };
  }

  /** The full search trace (candidates tried and their scores) from the last `compile()`. */
  get result(): MIPROv2Result | null {
    return this.lastResult;
  }

  async compile(
    program: Module<TInput, TOutput> | Pipeline,
    trainset: TrainingExample<TInput, TOutput>[]
  ): Promise<Module<TInput, TOutput>> {
    const mod = program as Module<TInput, TOutput>;
    if (typeof (mod as any).signature === 'undefined') {
      throw new Error('MIPROv2.compile expects a Module (with a signature), not a raw Pipeline');
    }
    this.log('MIPROv2: proposing instructions');
    const proposed = await this.proposeInstructions(mod);

    // Experience replay: warm-start the search with instructions that worked
    // before for a similar task fingerprint.
    const fingerprint = this.taskFingerprint(mod);
    const recalled = this.config.replayStore ? await this.recallPriorInstructions(this.config.replayStore, fingerprint) : [];
    const seen = new Set<string>();
    const instructions = [...recalled, ...proposed].filter((s) => (seen.has(s) ? false : (seen.add(s), true)));
    if (recalled.length > 0) this.log(`MIPROv2: warm-started with ${recalled.length} recalled instruction(s)`);
    this.log(`MIPROv2: ${instructions.length} candidate instructions`);

    const runId = this.config.tracer
      ? await this.config.tracer.startRun('MIPROv2', {
          program: mod.name,
          numTrials: this.config.numTrials,
          numCandidateInstructions: instructions.length,
          seed: this.config.seed,
          warmStarted: recalled.length > 0,
        })
      : undefined;

    this.log('MIPROv2: bootstrapping demos');
    const { labeled, bootstrapped } = await this.bootstrapDemos(mod, trainset);
    const allDemos = [...labeled, ...bootstrapped];
    this.log(`MIPROv2: ${labeled.length} labeled + ${bootstrapped.length} bootstrapped demos`);

    const evalSet = trainset.filter((ex) => ex.output !== undefined);
    const r = rng(this.config.seed);
    const trials: MIPROv2Result['trials'] = [];
    let best: { instruction: string; demos: TrainingExample<TInput, TOutput>[]; score: number } | null = null;

    const demoCounts = [0, Math.min(2, allDemos.length), allDemos.length].filter((n, i, a) => a.indexOf(n) === i);

    for (let t = 0; t < this.config.numTrials; t++) {
      const instruction = instructions[Math.floor(r() * instructions.length)];
      const numDemos = demoCounts[Math.floor(r() * demoCounts.length)] ?? 0;
      const demos = this.sample(allDemos, numDemos, r);
      const candidate = new OptimizedModule<TInput, TOutput>(mod.name, mod.signature, instruction, demos);
      const score = await this.scoreCandidate(candidate, evalSet);
      trials.push({ instruction, numDemos: demos.length, score });
      if (runId) await this.config.tracer!.logTrial(runId, { label: `trial-${t + 1}`, params: { numDemos: demos.length }, score });
      if (!best || score > best.score) best = { instruction, demos, score };
    }

    // Fallback: if there was nothing to evaluate, just take the first instruction + all demos.
    if (!best) best = { instruction: instructions[0], demos: allDemos, score: 0 };

    // Persist this compile's best for future warm-starts.
    if (this.config.replayStore) {
      try {
        await this.recordBest(this.config.replayStore, fingerprint, best.instruction, best.score, best.demos.length);
      } catch (err) {
        this.log(`replay record failed: ${err}`);
      }
    }

    this.optimizedProgram = new OptimizedModule<TInput, TOutput>(mod.name, mod.signature, best.instruction, best.demos);
    this.lastResult = {
      instruction: best.instruction,
      demos: best.demos,
      score: best.score,
      trials,
      warmStarted: recalled.length > 0,
      recalledInstructions: recalled.length,
    };
    if (runId) await this.config.tracer!.endRun(runId, { bestScore: best.score, trials: trials.length, instruction: best.instruction });
    this.log(`MIPROv2: best score ${best.score.toFixed(3)} with ${best.demos.length} demos`);
    return this.optimizedProgram;
  }

  /** A stable identity for a task — used to key experience-replay records. */
  private taskFingerprint(program: Module<TInput, TOutput>): string {
    const ins = program.signature.inputs.map((f) => `${f.name}:${f.type}`).join(',');
    const outs = program.signature.outputs.map((f) => `${f.name}:${f.type}`).join(',');
    return `${program.name}|in[${ins}]|out[${outs}]`;
  }

  /** Recall the best instructions from prior compiles of a similar task. */
  private async recallPriorInstructions(client: AgentDBClient, fingerprint: string): Promise<string[]> {
    try {
      const fpVec = client.hashEmbed(fingerprint);
      const hits = await client.search(fpVec, { k: Math.max(this.config.replayTopK * 6, 12) });
      const prior = hits
        .filter((h) => h.score > 0.95 && h.data.metadata?.type === 'mipro-best' && h.data.metadata?.fingerprint === fingerprint)
        .map((h) => ({ instruction: String(h.data.metadata.instruction ?? ''), score: Number(h.data.metadata.score ?? 0) }))
        .filter((p) => p.instruction.length > 0)
        .sort((a, b) => b.score - a.score);
      const seen = new Set<string>();
      const uniq = prior.filter((p) => (seen.has(p.instruction) ? false : (seen.add(p.instruction), true)));
      return uniq.slice(0, this.config.replayTopK).map((p) => p.instruction);
    } catch {
      return [];
    }
  }

  /** Record this compile's winning (instruction, score) for the task fingerprint. */
  private async recordBest(client: AgentDBClient, fingerprint: string, instruction: string, score: number, numDemos: number): Promise<void> {
    const fpVec = client.hashEmbed(fingerprint);
    await client.store(fpVec, { type: 'mipro-best', fingerprint, instruction, score, numDemos, ts: Date.now() });
  }

  private async proposeInstructions(program: Module<TInput, TOutput>): Promise<string[]> {
    const out: string[] = [];
    // The program's own prompt template (rendered on a probe input) is a candidate.
    try {
      const probe = Object.fromEntries(program.signature.inputs.map((f) => [f.name, ''])) as TInput;
      const own = program.promptTemplate(probe);
      if (own && own.trim()) out.push(own.trim().slice(0, 400));
    } catch {
      /* ignore */
    }
    // Ask the LM to propose a few instructions (best-effort).
    try {
      const lm = getLM();
      const n = Math.max(0, this.config.numCandidateInstructions - out.length - 1);
      if (n > 0) {
        const raw = await lm.generate(
          `Propose ${n} concise instruction strings (one per line, no numbering) for a task with inputs [${program.signature.inputs
            .map((f) => f.name)
            .join(', ')}] and outputs [${program.signature.outputs.map((f) => f.name).join(', ')}].`
        );
        for (const line of String(raw).split('\n').map((l) => l.replace(/^[-*\d.)\s]+/, '').trim()).filter(Boolean)) {
          out.push(line.slice(0, 400));
        }
      }
    } catch {
      /* LM unavailable — fall through to templates */
    }
    for (const t of DEFAULT_TEMPLATES) {
      if (out.length >= this.config.numCandidateInstructions) break;
      out.push(t);
    }
    // De-dup, keep at least one.
    const seen = new Set<string>();
    const uniq = out.filter((s) => (seen.has(s) ? false : (seen.add(s), true)));
    return uniq.length > 0 ? uniq.slice(0, this.config.numCandidateInstructions) : [DEFAULT_TEMPLATES[0]];
  }

  private async bootstrapDemos(
    program: Module<TInput, TOutput>,
    trainset: TrainingExample<TInput, TOutput>[]
  ): Promise<{ labeled: TrainingExample<TInput, TOutput>[]; bootstrapped: TrainingExample<TInput, TOutput>[] }> {
    const labeled = trainset.filter((ex) => ex.output !== undefined).slice(0, this.config.maxLabeledDemos);
    const bootstrapped: TrainingExample<TInput, TOutput>[] = [];
    const candidates = trainset.filter((ex) => ex.output === undefined).slice(0, this.config.maxBootstrappedDemos);
    for (const ex of candidates) {
      try {
        const output = await program.run(ex.input);
        if (this.metric(ex.input, output) >= this.config.minDemoScore) bootstrapped.push({ input: ex.input, output });
      } catch (err) {
        this.log(`bootstrap demo failed: ${err}`);
      }
    }
    return { labeled, bootstrapped };
  }

  private async scoreCandidate(candidate: OptimizedModule<TInput, TOutput>, evalSet: TrainingExample<TInput, TOutput>[]): Promise<number> {
    if (evalSet.length === 0) return 0;
    const batch = this.config.minibatchSize ? evalSet.slice(0, this.config.minibatchSize) : evalSet;
    let sum = 0;
    let n = 0;
    for (const ex of batch) {
      try {
        const output = await candidate.run(ex.input);
        sum += this.metric(ex.input, output, ex.output);
        n++;
      } catch {
        n++; // a crash on an example scores 0
      }
    }
    return n > 0 ? sum / n : 0;
  }

  private sample<T>(arr: T[], n: number, r: () => number): T[] {
    if (n >= arr.length) return [...arr];
    const idx = new Set<number>();
    while (idx.size < n) idx.add(Math.floor(r() * arr.length));
    return [...idx].sort((a, b) => a - b).map((i) => arr[i]);
  }

  save(filePath: string): void {
    if (!this.optimizedProgram) throw new Error('No optimized program to save. Run compile() first.');
    const safePath = safeResolvePath(filePath);
    fs.writeFileSync(
      safePath,
      JSON.stringify(
        {
          config: this.config,
          program: {
            name: this.optimizedProgram.name,
            signature: this.optimizedProgram.signature,
            instruction: this.optimizedProgram.instruction,
            demos: this.optimizedProgram.demos,
          },
          result: this.lastResult,
        },
        null,
        2
      )
    );
  }

  load(filePath: string): void {
    const safePath = safeResolvePath(filePath);
    let data: Record<string, any>;
    try {
      data = JSON.parse(fs.readFileSync(safePath, 'utf8'));
    } catch (err) {
      throw new Error(`Failed to parse saved state from ${safePath}: ${err instanceof Error ? err.message : String(err)}`);
    }
    this.optimizedProgram = new OptimizedModule(data.program.name, data.program.signature, data.program.instruction, data.program.demos ?? []);
    this.lastResult = data.result ?? null;
    if (data.config) this.config = data.config;
  }
}
